### ISSUE TITLE
Missing ServiceConnectorCreator

### ISSUE THREAD

**Issue by ipsi** [pivotal-cf/spring-cloud-sso-connector#3]
When I attempt to do something like the following:

``` java
@CloudScan
public class OAuthCloudConfig extends BaseOAuthConfig {

    @Autowired
    private SsoServiceInfo ssoServiceInfo;
}
```

I get a `BeanNotFound` exception, which seemed a bit weird.

Looking deeper, in the log file I see the following `Unable to create service for p-identity during service scanning. Skiping.`

This is because the `spring-cloud-sso-connector` project expects there to be a `org.springframework.cloud.service.ServiceConnectorCreator` class, but there is not for the SSO service.

**Comment by cdutra** [comment]
Hi,

The reason why we don't create a ServiceConnector is because we inject all the configuration through https://github.com/pivotal-cf/spring-cloud-sso-connector/blob/master/src/main/java/io/pivotal/spring/cloud/SsoServiceCredentialsListener.java

You can use the CloudFactory to retrieve the SsoServiceInfo: https://github.com/pivotal-cf/spring-cloud-sso-connector#java-applications.

Thanks!

**Comment by ipsi** [comment]
Yeah, I understand that's possible (and frankly it's probably a more sensible approach). I guess the question is why is it not the same as the other services? Have you found that the typical use-case for `SsoServiceInfo` is different from the rest (e.g. Mongo, MySQL, Rabbit, etc), such that you're better served with this approach?

I think this approach is more sensible WRT to non-CF services (e.g. all I have to do is add some environment variables and PRESTO! SSO is now configured), at least until we get the ability to specify labels and tags and the like on Cloud Foundry, but it's kinda annoying having two different ways to do things.

**Comment by cdutra** [comment]
Yes,  the use case is different since the services you mentioned have a DataSource in common. For the SSO service we don't have only one entity that configures/describes Spring OAuth 2.0 like the DataSource.
