### ISSUE TITLE
jwkTokenStore conflicts with oauth2 and spring boot 2

### ISSUE THREAD

**Issue by minhan-pivotal** [pivotal-cf/spring-cloud-sso-connector#9]
```
The bean 'jwkTokenStore', defined in class path resource [io/pivotal/spring/cloud/IssuerCheckConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$JwkTokenStoreConfiguration.class] and overriding is disabled.
```

Dependencies in build.gradle 
Spring boot version is 2.1.0.RELEASE
```
    implementation 'io.pivotal.spring.cloud:spring-cloud-sso-connector:2.1.3.RELEASE'

    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.cloud:spring-cloud-starter-oauth2')
    implementation('org.springframework.cloud:spring-cloud-starter-security')
    compileOnly('org.projectlombok:lombok')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
```

**Comment by TildeWill** [comment]
+1, same problem in our app.
springBootVersion = '2.1.0.RELEASE'
```
compile 'io.pivotal.spring.cloud:spring-cloud-sso-connector:2.1.3.RELEASE'
```

**Comment by ajdas** [comment]
+1 Same issue
springBootVersion = '2.1.1.RELEASE'
implementation('io.pivotal.spring.cloud:spring-cloud-sso-connector:2.1.3.RELEASE')

**Comment by ajdas** [comment]
Got it working by adding the following exclude

@SpringBootApplication(exclude= {io.pivotal.spring.cloud.IssuerCheckConfiguration.class})

**Comment by kolgepratik** [comment]
+1 Same issue

@SpringBootApplication(exclude= {io.pivotal.spring.cloud.IssuerCheckConfiguration.class}) 
Did not resolve this issue

**Comment by b2dt** [comment]
+1 same issue

@SpringBootApplication(exclude= {io.pivotal.spring.cloud.IssuerCheckConfiguration.class})
resolved it in the end, but would prefer a cleaner fix.

**Comment by danielbernier** [comment]
Hi.  Any definitive solution for this problem instead of a workaround?

**Comment by peterhaochen47** [comment]
@danielbernier This current library is only compatible with Spring Boot 1.5. The Spring Boot 2 compatible "connector" library will be published soon under the [java-cfenv](https://github.com/pivotal-cf/java-cfenv) library (currently the `java-cfenv/java-cfenv-boot-pivotal-sso` only supports Spring Boot 1.5).

**Comment by peterhaochen47** [comment]
This library is only compatible with Spring Boot 1.5 and Spring Security 2. If you are looking for a library that supports Spring Boot 2.1+ and Spring Security 5+, please refer to [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) and the updated [identity-sample-apps](https://github.com/pivotal-cf/identity-sample-apps)
